version: '3.8'
services:
  api:
    container_name: openai-poc
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
      - "9229:9229"
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: postgres-openai-poc
    restart: always
    image: ankane/pgvector
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - postgres_data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin_container_openai_poc
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - db:pgsql-server

volumes:
  postgres_data: {}
  dumps: {}
  pgadmin: {}
